# Generated by Django 3.1.14 on 2022-02-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=300, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('client_email', models.EmailField(max_length=254)),
                ('message_subject', models.CharField(max_length=75)),
                ('message', models.TextField()),
                ('message_date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='about1',
        ),
        migrations.DeleteModel(
            name='about2',
        ),
        migrations.DeleteModel(
            name='about3',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Con',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Contact1',
        ),
        migrations.DeleteModel(
            name='events',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='messagescommunications',
            name='messages_posted_by',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='feed',
        ),
        migrations.DeleteModel(
            name='MessagesCommunications',
        ),
    ]
